### PR TITLE
Revert the modified_at to original and add raw_Id and raw_ts instead

### PR DESCRIPTION
**Pull request by toileto**
## What's changed?

1. The `modified_at` on L1 is back, sourcing it from `$.modifiedAt`.
2. Added `raw_id` and `raw_ts` on L1 scripts
3. Modified the filter to use `raw_ts` on L2 scripts

## What's next?

1. Will backfill the entire L1-L2 tables from `2022-09-23 13:00:00 GMT+7` until latest date of the successful job.

### CODE REVIEW

**Comment by sagaekakristi** [comment]
should we use _raw_id and _raw_ts instead of raw_id and raw_ts to reduce the possibility of having the same column name from source?

**Comment by toileto** [comment]
> should we use _raw_id and _raw_ts instead of raw_id and raw_ts to reduce the possibility of having the same column name from source?

Updated to use `_raw_ts` and `_raw_id`

**Review by sagaekakristi — APPROVED** [review]
LGTM

**Review by fikrihaykal41 — COMMENTED** [review]
so far so good, tapi mau tanya, yang dibawa dari datalake raw `ts` atau `ts_ms`? soalnya kalau di tiket yg dibawa `ts_ms`
image

**Review by fikrihaykal41 — APPROVED** [review]
so far looks good, approved!

**Pull request merged**
