### PR TITLE
dma_logee_deliverydetails to airflow

### PR DESCRIPTION
**Pull request by RendiKustiawan**

### CODE REVIEW

**Review by ameliaksalwa — CHANGES_REQUESTED** [review]
punteun edit query sql-nya bukan di `bq_view`, tapi `dags -> source -> sql -> dwh -> L1 -> visibility`

**Review by toileto — APPROVED** [review]
Approved. Thank you Rendi buat kontribusinya selama ini yaaaa. 

Stay on top!

**Review by ameliaksalwa — APPROVED** [review]
Approved yey

**Review by toileto — APPROVED** [review]
Approved

**Pull request merged**
